from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_command(
    command: list[str],
    step_name: str,
    continue_on_error: bool,
) -> dict:
    print()
    print("=" * 70)
    print(f"Running step: {step_name}")
    print("=" * 70)
    print(" ".join(command))
    print()

    started_at = datetime.now().isoformat(timespec="seconds")

    completed = subprocess.run(
        command,
        text=True,
    )

    finished_at = datetime.now().isoformat(timespec="seconds")

    status = {
        "step": step_name,
        "command": command,
        "return_code": completed.returncode,
        "started_at": started_at,
        "finished_at": finished_at,
        "ok": completed.returncode == 0,
    }

    if completed.returncode != 0:
        message = f"Step failed: {step_name} with return code {completed.returncode}"
        if continue_on_error:
            print(f"WARNING: {message}")
        else:
            raise RuntimeError(message)

    return status


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2)


def write_markdown_summary(
    path: Path,
    payload: dict,
) -> None:
    lines: list[str] = []

    lines.append("# AutoPercept3D Showcase Export")
    lines.append("")
    lines.append("This folder was generated by `scripts/export_showcase_package.py`.")
    lines.append("")
    lines.append("## Configuration")
    lines.append("")
    for key, value in payload["config"].items():
        lines.append(f"- **{key}**: `{value}`")
    lines.append("")

    lines.append("## Generated outputs")
    lines.append("")
    for label, file_path in payload["outputs"].items():
        lines.append(f"- **{label}**: `{file_path}`")
    lines.append("")

    lines.append("## Pipeline steps")
    lines.append("")
    for step in payload["steps"]:
        icon = "✅" if step["ok"] else "❌"
        lines.append(f"### {icon} {step['step']}")
        lines.append("")
        lines.append("```bat")
        lines.append(" ".join(step["command"]))
        lines.append("```")
        lines.append("")
        lines.append(f"- return code: `{step['return_code']}`")
        lines.append(f"- started: `{step['started_at']}`")
        lines.append(f"- finished: `{step['finished_at']}`")
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- BEV IoU is a lightweight internal AABB metric, not official KITTI evaluation.")
    lines.append("- Tracklet replay is intended for qualitative temporal inspection.")
    lines.append("- Curated tracklets are a stricter subset for cleaner demo and reporting assets.")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run a one-command AutoPercept3D showcase export for frame, evaluation, tracklets, and GIF assets."
    )

    parser.add_argument("--dataset-root", type=str, required=True)
    parser.add_argument("--frame", type=str, default="000264")
    parser.add_argument("--start-index", type=int, default=250)
    parser.add_argument("--max-frames", type=int, default=20)
    parser.add_argument("--iou-threshold", type=float, default=0.10)
    parser.add_argument("--box-type", type=str, default="oriented", choices=["axis", "oriented"])
    parser.add_argument("--duration-ms", type=int, default=700)
    parser.add_argument("--output-dir", type=str, default="showcase_export")
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue running later steps even if an earlier step fails.",
    )

    args = parser.parse_args()

    project_root = Path.cwd()
    output_dir = Path(args.output_dir)

    frame_demo_dir = output_dir / "frame_demo"
    frame_eval_dir = output_dir / "frame_eval"
    batch_iou_dir = output_dir / "batch_iou"
    tracklet_replay_dir = output_dir / "tracklet_replay"
    tracklet_curation_dir = output_dir / "tracklet_curation"
    tracklet_demo_dir = output_dir / "tracklet_demo"

    output_dir.mkdir(parents=True, exist_ok=True)

    python_exe = sys.executable

    commands: list[tuple[str, list[str]]] = [
        (
            "single-frame demo assets",
            [
                python_exe,
                "scripts/export_demo_assets.py",
                "--dataset-root",
                args.dataset_root,
                "--frame",
                args.frame,
                "--output-dir",
                str(frame_demo_dir),
            ],
        ),
        (
            "single-frame BEV IoU evaluation",
            [
                python_exe,
                "scripts/evaluate_frame_iou.py",
                "--dataset-root",
                args.dataset_root,
                "--frame",
                args.frame,
                "--iou-threshold",
                str(args.iou_threshold),
                "--output-json",
                str(frame_eval_dir / f"eval_{args.frame}.json"),
                "--save-plot",
                str(frame_eval_dir / f"eval_{args.frame}.png"),
            ],
        ),
        (
            "batch BEV IoU evaluation",
            [
                python_exe,
                "scripts/run_batch_iou_evaluation.py",
                "--dataset-root",
                args.dataset_root,
                "--start-index",
                str(args.start_index),
                "--max-frames",
                str(args.max_frames),
                "--iou-threshold",
                str(args.iou_threshold),
                "--output-dir",
                str(batch_iou_dir),
            ],
        ),
        (
            "stable tracklet replay export",
            [
                python_exe,
                "scripts/render_tracklet_replay.py",
                "--dataset-root",
                args.dataset_root,
                "--start-index",
                str(args.start_index),
                "--max-frames",
                str(args.max_frames),
                "--box-type",
                args.box_type,
                "--output-dir",
                str(tracklet_replay_dir),
            ],
        ),
        (
            "high-quality tracklet curation",
            [
                python_exe,
                "scripts/curate_tracklets.py",
                "--tracklets-csv",
                str(tracklet_replay_dir / "stable_tracklets.csv"),
                "--output-dir",
                str(tracklet_curation_dir),
            ],
        ),
        (
            "tracklet GIF and contact sheet export",
            [
                python_exe,
                "scripts/export_tracklet_gif.py",
                "--frames-dir",
                str(tracklet_replay_dir / "frames"),
                "--output-dir",
                str(tracklet_demo_dir),
                "--duration-ms",
                str(args.duration_ms),
            ],
        ),
    ]

    print("=" * 70)
    print("AutoPercept3D showcase package export")
    print("=" * 70)
    print(f"Project root:    {project_root}")
    print(f"Dataset root:    {args.dataset_root}")
    print(f"Output dir:      {output_dir}")
    print(f"Frame:           {args.frame}")
    print(f"Sequence:        {args.start_index} to {args.start_index + args.max_frames - 1}")
    print(f"Box type:        {args.box_type}")
    print()

    steps: list[dict] = []

    for step_name, command in commands:
        step_status = run_command(
            command=command,
            step_name=step_name,
            continue_on_error=args.continue_on_error,
        )
        steps.append(step_status)

    manifest = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "config": {
            "dataset_root": args.dataset_root,
            "frame": args.frame,
            "start_index": args.start_index,
            "max_frames": args.max_frames,
            "iou_threshold": args.iou_threshold,
            "box_type": args.box_type,
            "duration_ms": args.duration_ms,
            "output_dir": str(output_dir),
        },
        "steps": steps,
        "outputs": {
            "frame_demo_dir": str(frame_demo_dir),
            "frame_metrics_csv": str(frame_demo_dir / f"frame_{args.frame}_metrics.csv"),
            "frame_result_json": str(frame_demo_dir / f"frame_{args.frame}_result.json"),
            "frame_eval_json": str(frame_eval_dir / f"eval_{args.frame}.json"),
            "frame_eval_plot": str(frame_eval_dir / f"eval_{args.frame}.png"),
            "batch_iou_csv": str(batch_iou_dir / "batch_iou_metrics.csv"),
            "tracklet_replay_dir": str(tracklet_replay_dir),
            "stable_tracklets_csv": str(tracklet_replay_dir / "stable_tracklets.csv"),
            "tracklet_frames_dir": str(tracklet_replay_dir / "frames"),
            "tracklet_curation_dir": str(tracklet_curation_dir),
            "curated_tracklets_csv": str(tracklet_curation_dir / "curated_tracklets.csv"),
            "curation_summary_json": str(tracklet_curation_dir / "curation_summary.json"),
            "tracklet_gif": str(tracklet_demo_dir / "tracklet_replay.gif"),
            "tracklet_contact_sheet": str(tracklet_demo_dir / "tracklet_replay_contact_sheet.png"),
        },
    }

    manifest_path = output_dir / "showcase_manifest.json"
    markdown_summary_path = output_dir / "SHOWCASE_SUMMARY.md"

    write_json(manifest_path, manifest)
    write_markdown_summary(markdown_summary_path, manifest)

    print()
    print("=" * 70)
    print("Showcase export complete")
    print("=" * 70)
    print(f"Manifest:         {manifest_path}")
    print(f"Markdown summary: {markdown_summary_path}")
    print()
    print("Main demo assets:")
    print(f"  Frame demo dir:       {frame_demo_dir}")
    print(f"  Frame eval plot:      {frame_eval_dir / f'eval_{args.frame}.png'}")
    print(f"  Batch IoU metrics:    {batch_iou_dir / 'batch_iou_metrics.csv'}")
    print(f"  Stable tracklets:     {tracklet_replay_dir / 'stable_tracklets.csv'}")
    print(f"  Curated tracklets:    {tracklet_curation_dir / 'curated_tracklets.csv'}")
    print(f"  Tracklet GIF:         {tracklet_demo_dir / 'tracklet_replay.gif'}")
    print(f"  Contact sheet:        {tracklet_demo_dir / 'tracklet_replay_contact_sheet.png'}")


if __name__ == "__main__":
    main()
